### ISSUE TITLE
__DIR__ requires PHP >= 5.3.0

### ISSUE THREAD

**Issue by speedy111** [Joomla-Ajax-Interface/Ajax-Session-Module#13]
If you'd like to support PHP 5.2.4+ (just like Joomla 2.5, let alone Joomla 1.5) then you can't use <code>____DIR____</code>, since it requires at least PHP 5.3.0. You can however use dirname(____FILE____). 

(don't mind the incorrect amount of underscores, github formatting...)

Cheers,
Jurian

**Comment by betweenbrain** [comment]
Thanks Jurian! That's a good point. I do wonder though, while Joomla 1.5/2.5 supports PHP 5.2.4+, if these extensions should as PHP 5.2 EOL was [January 2011](http://php.net/eol.php) and most hosts are upgrading their version of PHP, if they haven't already.

Definitely something to consider, or at least document.

**Comment by betweenbrain** [comment]
Closing as this seems to be an obsolete issue.
