### ISSUE TITLE
Usage of $_SESSION

### ISSUE THREAD

**Issue by speedy111** [Joomla-Ajax-Interface/Ajax-Session-Module#5]
I don't think using $_SESSION is secure. I recommend to use the following:

$session = JFactory::getSession();
$session->set('name', "value");

See also this link, but note that you shouldn't assign by reference (so use = in stead of =& ) http://docs.joomla.org/How_to_access_session_variables_set_by_an_external_script

**Comment by betweenbrain** [comment]
Thanks Jurian! This code actually started off as native PHP, then evolved to Joomla 1.5 and then to 2.5+ ;-)

I appreciate the code review and will make these changes. Thanks!

**Comment by speedy111** [comment]
Aha! You're welcome Matt :)

**Comment by betweenbrain** [comment]
Hi Jurian,

Thanks again for the report. This should be resolved with f2a0c197b96352270d813e71ec98037144d75375. Does that look good to you? Seems to work fine here.

**Comment by speedy111** [comment]
Hi Matt,

This code looks a lot better :+1:

**Comment by betweenbrain** [comment]
Thanks Jurian, I appreciate the help!
